### ISSUE TITLE
Send arbitrary waveform through the DAC

### ISSUE THREAD

**Issue by zhizhenzhong** [openquantumhardware/qick#110]
Hi folks,

I am wondering if it is possible to enable sending arbitrary waveform through the DAC using the QICK? I see that the RAveragerProgram supports in-assembly quick DAC value updates, but it only applies to regular waveform like sweeping. Is it possible to extend current function to arbitrary waveform? I think this can be a very useful usecase to extend the QICK to perform some photonic experiments.

**Comment by meeg** [comment]
I am not sure what you are asking here. Here are two guesses:

Arbitrary waveforms (pulses with an envelope defined as I/Q arrays) are already available by defining the envelope waveform with `QickProgram.add_pulse()` (https://qick-docs.readthedocs.io/en/latest/_autosummary/qick.qick_asm.html#qick.qick_asm.QickProgram.add_pulse) and declaring the pulse as "arb" style. For the special case of a Gaussian envelope, you can see the 00_Send_receive_pulse demo notebook.

If you need to do in-assembly updates to an envelope waveform, that is not generally possible since the tProcessor has no direct access to the envelope memory, it can only tell the generator which memory range (what address to start at, and what length) to play. In some cases you may be able to get what you want by making in-assembly updates to the envelope address or length.
