### ISSUE TITLE
What's the difference beetween tProcessor clock and RF reference clock.

### ISSUE THREAD

**Issue by tristanlorriaux** [openquantumhardware/qick#111]
Hi QICK team,

I don't really get what's the difference beetween tProcessor clock and RF reference clock.
I have a ZCU 216, so my tProcessor frequency is set to  430.080 MHz and the RF reference clock outside of the LMK04828B is set to 245.760 MHz. 
But do we agree that DACs  and ADC working frequencies are dependant of the tProcessor frequency? 
So what is the interest and the impact of the RF reference clock (I suppose the importance of this latter one beacause in the firmware doc, several fucntions are dedicated to it !).

Thank you in advance for your response to my (dumb?) issue. 

Best regards,
Tristan

**Comment by meeg** [comment]
The DAC and ADC working frequencies, the tProcessor frequency, and the RF reference frequency are all independent (which is to say all the clocks are generated from the RF reference by some multiply/divide relationships that are hard-coded in the firmware, but different firmwares can have different frequencies and none of these ratios are required to be 1).

The RF reference clock will never be relevant to your code or the interpretation of your results - it is of course important internally, since the QickSoc initialization needs to program the LMK with the correct reference clock.

If there are specific points where the documentation is leading you down the wrong path, let's clear those up - your confusion is probably not unique!
