### ISSUE TITLE
Using the P/N differencial ports on the XM500 board  (ZCU111)

### ISSUE THREAD

**Issue by JavierSerranoGarcia** [openquantumhardware/qick#121]
Hi @meeg , we want to use DACs 0, 1, and 2 but they are P/N differential pairs. We need to convert to complete signals in order to drive qubits or flux lines. Do you know which device we should use to do the conversion? or is there any other trick?

Thank you
Javi

**Comment by meeg** [comment]
Generally if you want to convert differential signals to single-ended, you need a balun or a differential-to-single-ended amplifier.

You can see on the ZCU111 user guide that the single-ended outputs on the XM500 are connected through baluns, e.g. Mini-Circuits TCM2-33WX+. Mini-Circuits does not seem to sell baluns in SMA-connector packages, but other companies do. 

Note that baluns are incapable of passing a DC signal, there is always some minimum frequency - not a problem for an RF drive, but may not work for a DC-coupled flux bias. If you need that, see https://github.com/openquantumhardware/qick/issues/81.

There is also a crude hack possible, where you put a terminator on one side of the differential pair and use the other side, through a DC-block. I can't recommend this but it's very easy.

**Comment by JavierSerranoGarcia** [comment]
Thank you so much for your advice. One last question is if the QICK firmware could be recompiled by changing the setting of the ports in the XDC file in order to get single-ended DC signals from some DACs.

Otherwise, the solution in #81 can work.

Now I am thinking of QICK RF board should solve all of these issues, no?

**Comment by meeg** [comment]
You cannot use the XDC to change the RF-DAC ports to single-ended, those are special hard blocks with a certain analog interface and the firmware cannot just tell them to become something different.

Yes, the RF board will certainly solve this problem since it has both baluns and DC amplifiers on every DAC channel, but it is total overkill if all you want is to be able to use all the DACs of a ZCU111. That is doable with off-the-shelf baluns or amplifiers, and will be much cheaper than the giant RF board that is really meant to integrate a lab's entire RF setup on a single board.

**Comment by JavierSerranoGarcia** [comment]
Thank you @meeg . I am buying this amplifier THS3215EVM and trying it. I will let to know

**Comment by JavierSerranoGarcia** [comment]
The amplifier THS3215EVM works OK with the board. Now we can send DC signals through the P/N ports.
