### ISSUE TITLE
incomplete files in building new firmwire

### ISSUE THREAD

**Issue by lucyfan7266** [openquantumhardware/qick#215]
ERROR: [Vivado 12-172] File or Directory '/Directory/hdl/vect2bits_16.v' does not exist

Is there a location that I can find the file? Thanks

**Comment by meeg** [comment]
It's this file: https://github.com/openquantumhardware/qick/blob/main/firmware/hdl/vect2bits_16.v

but you should not be getting this error if you followed the instructions in the README. Maybe your working directory is not the directory with the project script. If that doesn't help - please give me the full tcl console log from running the project script. Probably there is an earlier error or warning that tells you what the real problem is.

**Comment by meeg** [comment]
Duplicate of #212
