### ISSUE TITLE
Uable to run pscp to copy qick tool in RFSoC 4x2 Board

### ISSUE THREAD

**Issue by atifjafri** [openquantumhardware/qick#274]
I am trying to copy qick tool in RF SoC 4x2 board using pscp with folloiwng on windows terminal
D:\QICK\cloned_repo>pscp -r qick xilinx@192.168.1.58:/home/xilinx/jupyter_notebooks/. 
but everytime I give the password, it given message of Access denied

![image](https://github.com/user-attachments/assets/923dbdc5-572f-4f72-aafb-3a8afe6e4481)

I have copied the pscp.exe in the folder where I have cloned the qick. Before this I tried without copying the pscp.exe (only putty installed), however, with that it was unable to recongnize pscp.

**Comment by meeg** [comment]
Are you able to SSH to the board using the same password?

**Comment by atifjafri** [comment]
I use factory password of xilinx to access the following
![image](https://github.com/user-attachments/assets/fe799e8c-dee4-473d-b714-d617cd0982af)

**Comment by atifjafri** [comment]
RF SoC is connected to WLAN router through RJ45  cable and latptop is connected to wifi to access the board as shown in fig. of last message.

**Comment by meeg** [comment]
Right, you're showing me the Jupyter server - I was asking whether you were able to connect to the board using SSH (PuTTY, I guess), because that uses the same authentication as pscp. Jupyter and SSH/SCP have the same default passwords but work in different ways.

If you can't get pscp to work, you could zip the QICK repository, upload the .zip file through the Jupyter server, then open a terminal in Jupyter and use that to unzip the .zip file.

**Comment by atifjafri** [comment]
The solution you proposed is working. Thanks
