### ISSUE TITLE
Use more ADC ports on ZCU111

### ISSUE THREAD

**Issue by zhizhenzhong** [openquantumhardware/qick#77]
In the QICK overlay and also the example here https://github.com/openquantumhardware/qick/blob/main/qick_demos/00_Send_receive_pulse.ipynb, only two ADC ports (on ADC tile 0) are activated. Is there a code or design change possible to enable more ADC ports given that there are 8 of them on the ZCU111?

**Comment by meeg** [comment]
Correct, the standard firmware only uses two ADC ports; it's possible to recompile the firmware to add more readouts. The firmware source is provided, so in principle you can do this yourself, but we'd be happy to discuss what you need.

**Comment by zhizhenzhong** [comment]
> 

Thanks! I would like to add more ADCs (I also want to use ADC tile 1) to the ZCU111 QICK. Do you have a bitstream that already contains this function？ If I need to edie the vivado project with the block design in the firmware, could you please advise on some steps that I should follow?

**Comment by meeg** [comment]
I think this is such a bitstream (it's been a while since I made it so I don't remember the details):
https://slac.stanford.edu/~meeg/qick/fw/2022-02-07_4ad-4da-16k/

However - if you have a little experience working with block designs, you should be able to add readouts and generators by just copying the IP blocks and RF data converter channel configurations you see for the existing channels. Some things to look out for when adding channels on a new tile (some of these points appear in #57):
* we don't use multi-tile sync, so each DAC and ADC tile is its own clock domain - don't forget to add the Xilinx IPs for the clock domain crossings
* on "dual ADC" devices like the ZCU111, the ADC fabric clock coming out of the RF data converter needs to be doubled, so you need a clock doubler for each ADC
* the timing.xdc constraints file has some clock groups that you will need to modify

**Comment by zhizhenzhong** [comment]
Thanks @meeg! I will give a try.
